app:
  profiles: dev
  mysql:
    host: 127.0.0.1
    user: root
    password: '12345678'
    database: tmk
    waitForConnections: true
    connectionLimit: 10
    queueLimit: 0
  oAuth2Service:
    transport: 4
    options:
      url: localhost:33207
      package:
        - oauth
      protoPath:
        - resource/protobufs/oauth2.proto
